#!/bin/bash
#SBATCH --job-name=MPI-Default-%j
#SBATCH --time=00:10:00
#SBATCH --ntasks=16
#SBATCH --output=viking-logs/MPI-Default-%j.log
#SBATCH --partition=teach
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32
#SBATCH --mem-per-cpu=600mb
#SBATCH --exclusive
dir=$(pwd)

bench_dir='benchmarks/main/default'
test_dir='benchmarks/MPI/default'
n=16

mkdir -p $dir/$test_dir

time mpirun -n $n ./vortex -d 0.0025 -x 256 -y 128 --p
